version: '3'
services:
  node:
    container_name: frontend
    image: node:21.7.1-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
    command: npm run dev
    networks:
      vite:

networks:
  vite:
    external: true